[package]
name = "AnvilTest"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = "0.11.1"
alloy-contract = "0.11.1"
alloy-provider = { version = "0.11.1", features = ["anvil-node"] }
ethers = "2.0.14"
eyre = "0.6.12"
tokio = { version = "1", features = ["full"] }
